### ISSUE TITLE
Stuck at "Creating database"

### ISSUE THREAD

**Issue by nobuto-m** [canonical/mysql-router-k8s-operator#393]
## Steps to reproduce

It's a race condition (I guess), but the basic procedure is following the Sunbeam tutorial https://canonical.com/microstack/docs/single-node

## Expected behavior

The model will get green.

## Actual behavior

Some mysql-router instances get stuck at executing.

```
cinder-ceph-mysql-router/0*  active    idle       10.1.0.192
cinder-mysql-router/0*       waiting   executing  10.1.0.189
glance-mysql-router/0*       active    idle       10.1.0.239
horizon-mysql-router/0*      active    idle       10.1.0.146
keystone-mysql-router/0*     active    idle       10.1.0.249
mysql/0*                     active    idle       10.1.0.24          Primary
neutron-mysql-router/0*      active    idle       10.1.0.41
nova-api-mysql-router/0*     active    idle       10.1.0.96
nova-cell-mysql-router/0*    active    idle       10.1.0.162
nova-mysql-router/0*         active    idle       10.1.0.248
placement-mysql-router/0*    active    idle       10.1.0.183
```

## Versions

Operating system: 24.04 LTS

Juju CLI: 3.6.2-genericlinux-amd64

Juju agent: 3.6.2

mysql-k8s charm revision: 8.0/edge     234
mysql-router-k8s charm revision: 8.0/edge     593

k8s: v1.32.2  2487  latest/edge

## Log output

Juju debug log: 

```
unit-cinder-mysql-router-0: 03:37:17 DEBUG unit.cinder-mysql-router/0.juju-log backend-database:76: State of reconcile users requested_users=[<relations.database_provides._RelationThatRequestedUser object at 0x781e638194b0>], self._shared_users=[]
unit-cinder-mysql-router-0: 03:37:17 DEBUG unit.cinder-mysql-router/0.juju-log backend-database:76: Deleting user if exists before creating user
unit-cinder-mysql-router-0: 03:37:18 DEBUG unit.cinder-mysql-router/0.juju-log backend-database:76: Deleting username='relation-76_e16b38e133d943-75' must_exist=False
unit-cinder-mysql-router-0: 03:37:20 DEBUG unit.cinder-mysql-router/0.juju-log backend-database:76: Deleted file self=_Path('/tmp/mysqlsh_script.py')
unit-cinder-mysql-router-0: 03:37:20 DEBUG unit.cinder-mysql-router/0.juju-log backend-database:76: Deleted file self=_Path('/tmp/mysqlsh_error.json')
unit-cinder-mysql-router-0: 03:37:20 DEBUG unit.cinder-mysql-router/0.juju-log backend-database:76: Deleted username='relation-76_e16b38e133d943-75' must_exist=False
unit-cinder-mysql-router-0: 03:37:21 DEBUG unit.cinder-mysql-router/0.juju-log backend-database:76: Deleted user if exists before creating user
unit-cinder-mysql-router-0: 03:37:21 DEBUG unit.cinder-mysql-router/0.juju-log backend-database:76: Creating database='cinder' and username='relation-76_e16b38e133d943-75' with attributes='{"created_by_user": "relation-76_e16b38e133d943"}'
```

## Additional context

The creation request is in the relation data of mysql-router side.

```
cinder-mysql-router/0:
  workload-version: 8.0.41-0ubuntu0.22.04.1
  opened-ports: []
  charm: ch:amd64/mysql-router-k8s-593
  leader: true
  life: alive
  relation-info:
  - relation-id: 76
    endpoint: backend-database
    related-endpoint: database
    application-data:
      data: '{"database": "mysql_innodb_cluster_metadata", "extra-user-roles": "mysqlrouter",
        "requested-secrets": "[\"username\", \"password\", \"tls\", \"tls-ca\", \"uris\"]"}'
      database: mysql_innodb_cluster_metadata
      endpoints: mysql-primary.openstack.svc.cluster.local:3306
      read-only-endpoints: mysql-replicas.openstack.svc.cluster.local:3306
      secret-user: secret://e16b38e1-33d9-4340-8943-3ca244d1707e/cunbk5vmp25c7bhi6nf0
      version: 8.0.41-0ubuntu0.22.04.1
    related-units:
      mysql/0:
        in-scope: true
        data:
          egress-subnets: 10.152.183.29/32
          ingress-address: 10.152.183.29
          private-address: 10.152.183.29
```

The mysql server side didn't populate the relation data in return.

```
  - relation-id: 76
    endpoint: database
    related-endpoint: backend-database
    application-data:
      database: mysql_innodb_cluster_metadata
      extra-user-roles: mysqlrouter
      requested-secrets: '["username", "password", "tls", "tls-ca", "uris"]'
    related-units:
      cinder-mysql-router/0:
        in-scope: true
        data:
          egress-subnets: 10.152.183.244/32
          ingress-address: 10.152.183.244
          private-address: 10.152.183.244
```

And I only see this log related to cinder-mysql-router.

```
unit-mysql-0: 03:35:44 DEBUG unit.mysql/0.juju-log database:76: ops 2.15.0 up and running.
unit-mysql-0: 03:35:47 DEBUG unit.mysql/0.juju-log database:76: no relation on 'tracing': tracing not ready
unit-mysql-0: 03:35:47 DEBUG unit.mysql/0.juju-log database:76: Starting root trace with id='e21cbbbdafad76c54e5227bae73fd082'.
unit-mysql-0: 03:35:48 DEBUG unit.mysql/0.juju-log database:76: Emitting Juju event database_relation_changed.
unit-mysql-0: 03:35:48 DEBUG unit.mysql/0.juju-log database:76: Emitting custom event <DatabaseRequestedEvent via MySQLOperatorCharm/DatabaseProvides[database]/on/database_requested[163]>.
unit-mysql-0: 03:35:51 DEBUG unit.mysql/0.juju-log database:76: Updating pod labels
unit-mysql-0: 03:36:04 WARNING unit.mysql/0.juju-log database:76: Kubernetes service already exists
unit-mysql-0: 03:36:04 DEBUG unit.mysql/0.juju-log database:76: Getting InnoDB version
unit-mysql-0: 03:36:08 DEBUG unit.mysql/0.juju-log database:76: Checking for Kubernetes service endpoint
unit-mysql-0: 03:36:08 DEBUG unit.mysql/0.juju-log database:76: Kubernetes service endpoint ready
unit-mysql-0: 03:36:17 INFO unit.mysql/0.juju-log database:76: Created user for app cinder-mysql-router
unit-mysql-0: 03:36:20 INFO juju.worker.uniter.operation ran "database-relation-changed" hook (via hook dispatching script: dispatch)
```

[mysql_0_debug.log](https://github.com/user-attachments/files/18794323/mysql_0_debug.log)

[cinder-mysql-router_0_debug.log](https://github.com/user-attachments/files/18794324/cinder-mysql-router_0_debug.log)
